### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by fivdi** [fivdi/spi-device#18]
Some of the tests no longer function as expected on Linux version 5.4.79-v7+ and need to be updated.
See also #16.

Here is the console output shown when the tests are run:

```console
default-options
node:assert:107
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: default chipSelectHigh incorrect
    at checkDefaultOptions (/home/pi/mcp-spi-adc/node_modules/spi-device/test/default-options.js:8:10)
    at checkOptions (/home/pi/mcp-spi-adc/node_modules/spi-device/test/default-options.js:19:3)
    at Object.<anonymous> (/home/pi/mcp-spi-adc/node_modules/spi-device/test/default-options.js:30:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: true,
  expected: false,
  operator: 'strictEqual'
}
options
options-sync
node:assert:107
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: can't set chipSelectHigh
    at Object.<anonymous> (/home/pi/mcp-spi-adc/node_modules/spi-device/test/options-sync.js:32:8)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: 'strictEqual'
}
message-size
/home/pi/mcp-spi-adc/node_modules/spi-device/test/message-size.js:30
  mcp3008.transferSync(createMessage(511)); // works
          ^

Error: EMSGSIZE, Message too long
    at transferAsManyAsPossible (/home/pi/mcp-spi-adc/node_modules/spi-device/test/message-size.js:30:11)
    at Object.<anonymous> (/home/pi/mcp-spi-adc/node_modules/spi-device/test/message-size.js:66:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  errno: 90,
  code: 'EMSGSIZE',
  syscall: 'transferSync'
}
transfer
```

**Comment by fivdi** [comment]
Fixed by 9fa6c12b8718ea32f209bb37a53b5d95604dffbd and 5ee14a52632c3fe68b24a0dc41c2088124566680.
